package templates;

public class CxTermsOfUse {
	public static String run() {
		return	"<p>This Terms of Use covers Martin Jelin developer of Checkout Express and his Affiliates\' (collectively, &quot;Checkout Express&quot;) web sites, mobile-optimized versions of the web sites, and digital applications to which this Terms of Use is linked (collectively, &quot;Covered Sites&quot;). As used in this Terms of Use, an entity controlling, controlled by, or under common control with another entity shall be deemed to be an &quot;Affiliate&quot;, where control means ownership of 15% or more of the voting stock. Certain features of the Covered Sites may be subject to additional guidelines, terms, or rules, which will be posted on the Covered Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into this Agreement. Capitalized terms not otherwise defined in this Agreement have the meaning given to such term in the Checkout Express privacy policy. The privacy policy is hereby incorporated by this reference into this Agreement.</p>"+
			""+
			"<p>THESE TERMS OF USE (&quot;AGREEMENT&quot;) SETS FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF THE COVERED SITES. BY ACCESSING OR USING THE COVERED SITES, YOU ARE ACCEPTING THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT) AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT). IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THIS AGREEMENT, DO NOT ACCESS AND/OR USE THE COVERED SITES.</p>"+
			""+
			"<p><strong>1. Username and Passwords.</strong> When you create a User Registration (as described in the Privacy Policy), you represent and warrant that: (a) all required registration information you submit is truthful and accurate; and (b) you will maintain the accuracy of such information. You will be responsible for maintaining the confidentiality of your User Registration, and we will not be responsible for misuse of your User Registration by any third party, whether authorized by you or not. You are responsible for all activities that occur under your User Registration. You agree to immediately notify Newspaper of any unauthorized use, or suspected unauthorized use of your User Registration or any other breach of security. Newspaper cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.</p>"+
			""+
			""+
			"<h1>2. LICENSES</h1>"+
			""+
			"<p>2.1 License. Subject to the terms of this Agreement, Checkout Express grants you a non-transferable, non-exclusive, license to use the Covered Sites for your personal, noncommercial use. Subject to the terms of this Agreement, Checkout Express grants you a non-transferable, non-exclusive, license to install and use the software Checkout Express makes available for mobile devices (&quot;Apps&quot;), in executable object code format only, solely on your own handheld mobile device and for your personal, noncommercial use. For the avoidance of doubt, Apps are deemed part of the Covered Sites.</p>"+
			""+
			"<p>2.2 Certain Restrictions. The rights granted to you in this Agreement are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Covered Sites; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Covered Sites; (c) you shall not access the Covered Sites in order to build a similar or competitive service; and (d) except as expressly stated herein, no part of the Covered Sites may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Any future release, update, or other addition to functionality of the Covered Sites shall be subject to the terms of this Agreement. All copyright and other proprietary notices on any Covered Sites content must be retained on all copies thereof.</p>"+
			""+
			"<p>2.3 Open Source Software. Certain items of independent, third-party code may be included in the App that are subject to open source licenses (&quot;Open Source Software&quot;). Such Open Source Software is licensed under the terms of the license that accompanies such Open Source Software. Nothing in this Agreement limits your rights under, or grants you rights that supersede, the terms and conditions of any applicable end user license for such Open Source Software.</p>"+
			""+
			"<p>2.4 Application Store. You acknowledge and agree that the availability of the App is dependent on the third party from which you received the App, e.g., the Apple iPhone store (&quot;Application Store&quot;). You acknowledge that this Agreement is between you and Checkout Express and not with the Application Store. Each Application Store may have its own terms and conditions to which you must agree before downloading the App from it. You agree to comply with, and your license to use the App is conditioned upon your compliance with, all applicable terms and conditions of the applicable Application Store.</p>"+
			""+
			"<p>2.5 Wireless Addresses, Short Message Services and Wireless Internet. By providing us your wireless email address or by signing up for any SMS, WAP, or Mobile Service (each as described in the Privacy Policy), you agree to the following: Our wireless carriers and providers are not responsible for the content of our wireless services or any of the messages you may receive from us. You acknowledge and agree that the wireless email, SMS, WAP and Mobile Services are provided via wireless systems which use radios (and other means) to transmit communications over complex networks. We do not guarantee that your use of such services will be private or secure, and we are not liable to you for any lack of privacy or security you may experience. You are fully responsible for taking precautions and providing security measures best suited for your situation and intended use of the services.</p>"+
			""+
			"<p>2.6 Modification. Checkout Express reserves the right, at any time, to modify, suspend, or discontinue the Covered Sites or any part thereof with or without notice. You agree that Checkout Express will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Covered Sites or any part thereof.</p>"+
			""+
			""+
			"<h1>3. OWNERSHIP AND FEEDBACK</h1>"+
			""+
			"<p>3.1 Excluding your User Content (defined below), you acknowledge that all the intellectual property rights, including copyrights, patents, trade marks, and trade secrets, in the Covered Sites are owned by Checkout Express or Checkout Express\' licensors. The provision of the Covered Sites does not transfer to you or any third party any rights, title or interest in or to such intellectual property rights. Checkout Express and its suppliers reserve all rights not granted in this Agreement.</p>"+
			""+
			"<p>3.2 If you provide Checkout Express any feedback or suggestions regarding the Covered Sites (&quot;Feedback&quot;), you hereby assign to Checkout Express all rights in the Feedback and agree that Checkout Express shall have the right to use such Feedback and related information in any manner it deems appropriate. Checkout Express will treat any Feedback you provide to Checkout Express as non-confidential and non-proprietary. You agree that you will not submit to Checkout Express any information or ideas that you consider to be confidential or proprietary.</p>"+
			""+
			"<h1>4. USER CONTENT</h1>"+
			""+
			"<p><strong>4.1 User Content.</strong> &quot;User Content&quot; means any and all information and content that a user submits to, or uses with, the Covered Sites (e.g., photos, audio, video, messages, text, files, or other content you provide us). You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that makes you or any third party personally identifiable. You hereby represent and warrant that your User Content does not violate the Acceptable Use Policy (defined below). You may not state or imply that your User Content is in any way provided, sponsored or endorsed by Checkout Express. Because you alone are responsible for your User Content (and not Checkout Express), you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy. Checkout Express is not obligated to backup any User Content and User Content may be deleted at anytime. You are solely responsible for creating backup copies of your User Content if you desire. Under no circumstance will Checkout Express be liable for any inaccuracy or defect in any User Content.</p>"+
			""+
			"<p><strong>4.2 License.</strong> You hereby grant, and you represent and warrant that you have the right to grant, to Checkout Express an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, and to grant sublicenses of the foregoing, for any lawful purpose. You agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content.</p>"+
			""+
			"<p><strong>4.3 Acceptable Use Policy.</strong> The following sets forth Checkout Express\' &quot;Acceptable Use Policy&quot;:</p>"+
			"<ol>"+
			"\t<li>You agree not to post, email, or otherwise make available User Content:"+
			"\t<ul>"+
			"\t\t<li>that is unlawful, harmful, threatening, abusive, harassing, defamatory, pornographic, libelous, or invasive of another\'s privacy, or harmful to minors in any way;</li>"+
			"\t\t<li>that harasses, degrades, intimidates or is hateful toward an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</li>"+
			"\t\t<li>that includes personal or identifying information about another person without that person\'s explicit consent.</li>"+
			"\t\t<li>that is false, deceptive, misleading, deceitful, misinformative, constitute &quot;bait and switch&quot; or impersonation of any person or entity;</li>"+
			"\t\t<li>that contains your own or a third party\'s advertising, branding or promotional content;</li>"+
			"\t\t<li>that is unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise;</li>"+
			"\t\t<li>that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right;</li>"+
			"\t\t<li>restrict or inhibit any other user from using and enjoying the Checkout Express sites or the Checkout Express services offered on them;</li>"+
			"\t\t<li>that includes your personal information, such as telephone number, street address, last name, URL or email address;</li>"+
			"\t\t<li>that is a &quot;cut and paste&quot; of private messages from other users;</li>"+
			"\t\t<li>that re-broadcasts any User Content that violates these terms; or</li>"+
			"\t\t<li>that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.</li>"+
			"\t</ul></li>"+
			"\t<li>In addition, you agree not to use the Covered Sites to:"+
			"\t<ul>"+
			"\t\t<li>upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer system or data;</li>"+
			"\t\t<li>harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent;</li>"+
			"\t\t<li>interfere with, disrupt, or create an undue burden on servers or networks connected to the Covered Sites or violate the regulations, policies or procedures of such networks;</li>"+
			"\t\t<li>attempt to gain unauthorized access to the Covered Sites, other computer systems or networks connected to or used together with the Covered Sites, through password mining or other means;</li>"+
			"\t\t<li>tamper with any copyright protection mechanisms applicable to content on any Covered Sites;</li>"+
			"\t\t<li>introduce software or automated agents or scripts to the Covered Sites so as to produce multiple accounts, generate automated searches, requests and queries, or to strip, scrape, or mine data from the Covered Sites (except that we grant the operators of public search engines revocable permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials).</li>"+
			"\t</ul></li>"+
			"</ol>"+
			""+
			"<p><strong>4.4 Enforcement.</strong> We reserve the right (but have no obligation) to review any User Content, investigate, and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of this Agreement or otherwise create liability for us or any other person. Such acts may include removing or modifying your User Content, terminating your User Registration, and/or reporting you to law enforcement authorities. If Checkout Express elects to modify User Content, Checkout Express nonetheless assumes no responsibility for the User Content.</p>"+
			""+
			"<p><strong>4.5 Other Users.</strong> Each Covered Site user is solely responsible for any and all of its User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content, and we assume no responsibility for any User Content. Your interactions with other Covered Site users are solely between you and such user. You agree that Checkout Express will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Covered Site user, we are under no obligation to become involved. You acknowledge that other users may post comments about your User Content which may be derogatory, and Checkout Express has no obligation to monitor or delete any such User Content.</p>"+
			""+
			"<p><strong>4.6 Release.</strong> You hereby release and forever discharge us (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or relates directly or indirectly to, any interactions with, or act or omission of, other Covered Site users. IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: &quot;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.&quot;</p>"+
			""+
			""+
			"<p><strong>5. INDEMNITY.</strong> You agree to indemnify and hold Checkout Express (and its officers, employees, contractors, and agents) harmless, including costs and attorneys\' fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Covered Sites, (b) your User Content, (c) your violation of this Agreement; or (d) your violation of applicable laws or regulations. Checkout Express reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of Checkout Express. Checkout Express will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>"+
			""+
			""+
			"<h1>6. DISCLAIMERS</h1>"+
			""+
			"<p>THE COVERED SITES ARE PROVIDED &quot;AS-IS&quot; AND &quot;AS AVAILABLE&quot; AND WE (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE COVERED SITES: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.</p>"+
			""+
			"<p>DUE TO THE INHERENT NATURE OF THE INTERNET, WE CANNOT GUARANTEE THAT INFORMATION, DURING TRANSMISSION THROUGH THE INTERNET OR WHILE STORED ON OUR SYSTEM OR OTHERWISE IN OUR CARE, WILL BE ABSOLUTELY SAFE FROM INTRUSION BY OTHERS, SUCH AS HACKERS. Checkout Express ASSUMES NO LIABILITY FOR ANY ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMMUNICATIONS LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, OR ALTERATION OF, ANY USER CONTENT. Checkout Express IS NOT RESPONSIBLE FOR ANY PROBLEMS OR TECHNICAL MALFUNCTION OF ANY TELEPHONE NETWORK OR LINES, COMPUTER ONLINE SYSTEMS, SERVERS OR PROVIDERS, COMPUTER EQUIPMENT, SOFTWARE, OR FAILURE OF ANY EMAIL DUE TO TECHNICAL PROBLEMS OR TRAFFIC CONGESTION ON THE INTERNET OR ON ANY OF THE COVERED SITES OR COMBINATION THEREOF, INCLUDING ANY INJURY OR DAMAGE TO USERS OR TO ANY PERSON\'S COMPUTER RELATED TO OR RESULTING FROM PARTICIPATION IN ANY ACTIVITIES ON THE COVERED SITES OR DOWNLOADING MATERIALS. YOU UNDERSTAND THAT IF YOU DOWNLOAD ANY MATERIAL, YOU DO SO AT YOUR SOLE RISK. UNDER NO CIRCUMSTANCES SHALL Checkout Express BE RESPONSIBLE FOR ANY LOSS OR DAMAGE, INCLUDING PERSONAL INJURY OR DEATH, RESULTING FROM USE OF THE COVERED SITES, ANY CONTENT POSTED ON OR THROUGH THE COVERED SITES, OR CONDUCT OF ANY USERS OF THE COVERED SITES, WHETHER ONLINE OR OFFLINE. WE CAN, WHENEVER WE WANT, EDIT OR DELETE ANY CONTENT DISPLAYED ON THE COVERED SITES. YOU USE THE COVERED SITES AT YOUR OWN RISK. SOME AREAS OF OUR COVERED SITES OFFER ADVICE FROM A VARIETY OF PROVIDERS, WHO MAY BE AFFILIATED WITH Checkout Express OR MEMBER OF THE USER COMMUNITY; SUCH ADVICE IS FOR ENTERTAINMENT ONLY AND NOT AS TREATMENT OR REMEDY FOR AN INDIVIDUAL CIRCUMSTANCE. Checkout Express CANNOT GUARANTEE AND DOES NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE COVERED SITES.</p>"+
			""+
			"<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>"+
			""+
			"<h1>7. LIMITATION ON LIABILITY</h1>"+
			""+
			"<p>IN NO EVENT SHALL WE (AND OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT OR YOUR USE OF, OR INABILITY TO USE, THE COVERED SITES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>"+
			""+
			"<p>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU\'VE PAID Checkout Express IN THE PRIOR 12 MONTHS (IF ANY). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT. YOU AGREE THAT OUR SUPPLIERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT.</p>"+
			""+
			"<p>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>"+
			""+
			"<p><strong>8. Third Party Sites &amp; Ads.</strong> The Covered Sites might contain links to third party websites, services, and advertisements for third parties (collectively, &quot;Third Party Sites &amp; Ads&quot;). Such Third Party Sites &amp; Ads are not under the control of Newspaper and Newspaper is not responsible for any Third Party Sites &amp; Ads. Newspaper provides these Third Party Sites &amp; Ads only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Sites &amp; Ads. You use all Third Party Sites &amp; Ads at your own risk. When you link to a Third Party Site &amp; Ad, the applicable third party\'s terms and policies apply, including the third party\'s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third Party Sites &amp; Ads.</p>"+
			""+
			"<p><strong>9. TERM AND TERMINATION.</strong> Subject to this Section, this Agreement will remain in full force and effect while you use the Covered Sites. We may (a) suspend your rights to use the Covered Sites (including your User Registration) or (b) terminate this Agreement, at any time for any reason at our sole discretion, including for any use of the Covered Sites in violation of this Agreement. Upon termination of this Agreement, your User Registration and right to access and use the Covered Sites will terminate immediately. You understand that any termination of your User Registration involves deletion of your User Content associated therewith from our live databases. Checkout Express will not have any liability whatsoever to you for any termination of this Agreement, including for termination of your User Registration or deletion of your User Content. Even after this Agreement is terminated, the following provisions of this Agreement will remain in effect: Sections 3-11.</p>"+
			""+
			"<h1>10. COPYRIGHT POLICY.</h1>"+
			""+
			"<p>10.1 In accordance with the provisions of the Digital Millennium Copyright Act, 17 USC sec. 512, our Covered Sites have designated an agent to receive notices of claims of copyright infringement: Martin Jelin, 1091 Morewood Ave, Pittsburgh, PA, 15213. If you believe your copyright has been infringed, you may provide us with notice. To be effective, the notification must be a written communication that includes the following:</p>"+
			"<ul>"+
			"\t<li>A physical or electronic signature of person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>"+
			"\t<li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</li>"+
			"\t<li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;</li>"+
			"\t<li>Information reasonably sufficient to permit us to contact you, including an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</li>"+
			"\t<li>A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>"+
			"\t<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>"+
			"</ul>"+
			""+
			"<p>We may give notice to our users that we have received a notice of infringement by means of a general notice on our site, electronic mail to a user\'s e-mail address in our records, or by written communication sent by first-class mail to a user\'s physical address in our records. If you receive such a notice, you may provide counter-notification in writing to the designated agent that includes the information below. To be effective, the counter-notification must be a written communication that includes the following:</p>"+
			"<ul>"+
			"\t<li>Your physical or electronic signature;</li>"+
			"\t<li>Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;</li>"+
			"\t<li>A statement from you under the penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and</li>"+
			"\t<li>Your name, physical address and telephone number, and a statement that you consent to the jurisdiction of a Federal District Court for the judicial district in which your physical address is located, or if your physical address is outside of the United States, for the judicial district in which our offices are located, and that you will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person.</li>"+
			"</ul>"+
			""+
			"<p>We have a policy of terminating access to our Covered Sites of any user who repeatedly infringes the proprietary rights of any third party.</p>"+
			""+
			"<h1>11. GENERAL</h1>"+
			""+
			"<p><strong>11.1 Changes to Terms of Use.</strong> This Agreement is subject to occasional revision, and if we make any substantial changes, we may notify you by prominently posting notice of the changes on our Site. Any changes to this agreement will be effective upon the earlier of thirty (30) calendar days following our posting of notice of the changes on our Site. These changes will be effective immediately for new users of our Covered Sites. Continued use of our Covered Sites following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>"+
			""+
			"<h2>11.2 Dispute Resolution. PLEASE READ THIS CAREFULLY. IT AFFECTS YOUR RIGHTS.</h2>"+
			""+
			"<ol>"+
			"\t<li>Except for either party\'s claims of infringement or misappropriation of the other party\'s patent, copyright, trademark, or trade secret, any and all disputes between you and Checkout Express arising under or related in any way to this Agreement, must be resolved through binding arbitration as described in this section. This agreement to arbitrate is intended to be interpreted broadly. It includes, but is not limited to, all claims and disputes relating to your use of any of the Covered Sites.</li>"+
			"\t<li>YOU AGREE THAT BY ENTERING INTO THIS AGREEMENT, YOU AND Checkout Express ARE EACH WAIVING THE RIGHT TO TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. YOU AND Checkout Express AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. ANY ARBITRATION WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED.</li>"+
			"\t<li>The arbitration will be governed by the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes of the American Arbitration Association (&quot;AAA&quot;), as modified by this section. For any claim where the total amount of the award sought is $10,000 or less, the AAA, you and Checkout Express must abide by the following rules: (a) the arbitration shall be conducted solely based on written submissions; and (b) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties. If the claim exceeds $10,000, the right to a hearing will be determined by the AAA rules, and the hearing (if any) must take place in your choice of the following locations: Pittsburgh, PA. The arbitrator\'s ruling is binding and may be entered as a judgment in any court of competent jurisdiction. In the event this agreement to arbitrate is held unenforceable by a court, then the disputes that would otherwise have been arbitrated shall be exclusively brought in the state or federal courts located in New York City, New York. Claims of infringement or misappropriation of the other party\'s patent, copyright, trademark, or trade secret shall be exclusively brought in the state and federal courts located in New York City, New York.</li>"+
			"\t<li>This Agreement shall be governed by and construed solely and exclusively in accordance with the laws of the State of New York, USA without giving effect to any law that would result in the application of the law of another jurisdiction.</li>"+
			"</ol>"+
			""+
			"<p><strong>11.3 Entire Agreement.</strong> This Agreement (including the Privacy Policy) constitutes the entire agreement between you and us regarding the use of the Covered Sites. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word including means including without limitation. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Your relationship to Checkout Express is that of an independent contractor, and neither party is an agent or partner of the other. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Checkout Express\' prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of this Agreement shall be binding upon assignees.</p>";
	}
}